# .streamlit/secrets.toml
# 사용자 정의 비밀번호 (예: 관리자 접근 제한용)
password_gai = "941023"
password_update = "231113"

# 구글 API 키 (필요시만 사용)
GOOGLE_API_KEY = "AIzaSyA51gR7K-EGeT4-lRznqaNM4FMhmDdnes0"

# 연결할 Google Sheet 정보
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1Y96CU1MtQct7IJweKCx67QS_YqKErDnIUpcfS9g67DI/edit#gid=0"

# Google Service Account 인증 정보 (gspread용)
[gcp_service_account]
type = "service_account"
project_id = "graceful-matter-423500-t6"
private_key_id = "bc20a72ec851585413c45fd954c5ee8bf99a32ba"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCU51m4DPpPTtzL
gEWxsxo49V4Wv5YlUY/Ql+OR7mKjRH9320Ae+DQSQ1QsTDv868RDlw+t2D2FWfQA
...
22iv+Q==
-----END PRIVATE KEY-----"""
client_email = "amateur-baseball@graceful-matter-423500-t6.iam.gserviceaccount.com"
client_id = "106097781115212949770"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/amateur-baseball%40graceful-matter-423500-t6.iam.gserviceaccount.com"
